FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:3.7-buster-build

WORKDIR /usr/app
COPY pip.conf /etc/

RUN install_packages \
        jq \
        moreutils \
        libopenjp2-7 \
        libfreetype6-dev \
        libjpeg-dev \
        libtiff5

COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY src ./src
COPY balena-run.sh ./
COPY config.json ./

RUN chmod +x balena-run.sh

CMD ./balena-run.sh
