FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:3.7-buster

RUN install_packages \
        jq \
        moreutils \
        libopenjp2-7 \
        libfreetype6-dev \
        libjpeg-dev \
        libtiff5

WORKDIR /usr/app
COPY ./requirements.txt .
RUN pip install -r requirements.txt --index-url=https://www.piwheels.org/simple

COPY src ./src
COPY balena-run.sh ./
COPY config.sample.json ./

CMD ./balena-run.sh
